# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 'Default'

steps:

- script: |
    dir
  displayName: 'Check current directory'

- script: |
    appscansrccli scr cli_script.txt
  displayName: 'Perform AppScan Source SAST Scan, Generate PDF report, or publish to ASE'

#- script: |
#py "C:\appscan-issue-gateway\AIG_Client\AIG_GenericClient.py" localhost 4444 C:\appscan-issue-gateway\AIG_Client\job.json
#displayName: 'Publish to Jira'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/s/report_FP.pdf'
    publishLocation: 'pipeline'
